name: 機能要望
description: 新機能の提案を行う
title: "[機能要望] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        新機能の提案をありがとうございます。以下の情報を提供してください。

  - type: textarea
    id: description
    attributes:
      label: 提案する機能
      description: どのような機能を追加したいですか？
      placeholder: 例：ダークモードの追加
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: なぜ必要ですか？
      description: この機能がどのような問題を解決しますか？
      placeholder: 例：夜間の作業時に目が疲れにくくなる
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 他に検討した解決方法はありますか？
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: その他
      description: 参考情報やスクリーンショットがあれば追加してください
    validations:
      required: false